# Generated by Django 5.1.2 on 2024-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_useranswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="quiz_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
